services:
  marcador-rentoy:
    image: f1rul4yx/marcador-rentoy:latest
    container_name: marcador-rentoy
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - TZ=Europe/Madrid
      - NODE_ENV=production
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
